module.exports = {
  HIGH_SPENDING_RATIO_THRESHOLD: 0.6,
  HEALTHY_SAVINGS_THRESHOLD: 0.2,
  CATEGORY_ANOMALY_ZSCORE_THRESHOLD: 1.5,
  WEEK_OVER_WEEK_SURGE_PCT_THRESHOLD: 0.5,
  SAME_DAY_REPEAT_COUNT_THRESHOLD: 3,
  WEEKEND_SPENDING_RATIO_THRESHOLD: 0.5,
  SINGLE_CATEGORY_DOMINANCE_RATIO_THRESHOLD: 0.5,
  MIN_WEEKS_FOR_ANOMALY_DETECTION: 3,
};
